#!/usr/bin/env node
/**
 * clawpilot init — Interactive setup for ClawPilot.
 *
 * Run from inside the ClawPilot repo clone:
 *   npx clawpilot-init
 *
 * What it does:
 *   1. Generates .env with your configuration
 *   2. Generates .vscode/mcp.json for any workspace you point it at
 *   3. Walks through Teams webhook setup with copy-paste instructions
 */
import { createInterface } from "readline/promises";
import { writeFileSync, existsSync, mkdirSync, readFileSync } from "fs";
import { resolve, join } from "path";
import { stdin, stdout } from "process";

const rl = createInterface({ input: stdin, output: stdout });

const BOLD = "\x1b[1m";
const DIM = "\x1b[2m";
const GREEN = "\x1b[32m";
const YELLOW = "\x1b[33m";
const CYAN = "\x1b[36m";
const RESET = "\x1b[0m";

function banner() {
  console.log(`
${BOLD}🦀🤖 ClawPilot Setup${RESET}
${DIM}Bridge GitHub Copilot agent sessions with Microsoft Teams${RESET}
`);
}

async function ask(question: string, defaultValue?: string): Promise<string> {
  const suffix = defaultValue ? ` ${DIM}(${defaultValue})${RESET}` : "";
  const answer = await rl.question(`${CYAN}?${RESET} ${question}${suffix}: `);
  return answer.trim() || defaultValue || "";
}

async function confirm(question: string, defaultYes = true): Promise<boolean> {
  const hint = defaultYes ? "Y/n" : "y/N";
  const answer = await rl.question(`${CYAN}?${RESET} ${question} ${DIM}(${hint})${RESET}: `);
  if (!answer.trim()) return defaultYes;
  return answer.trim().toLowerCase().startsWith("y");
}

function success(msg: string) {
  console.log(`${GREEN}✔${RESET} ${msg}`);
}

function info(msg: string) {
  console.log(`${YELLOW}→${RESET} ${msg}`);
}

// ── Resolve paths ────────────────────────────────────────────
function findRepoRoot(): string {
  // Walk up from this script to find package.json with name "clawpilot"
  let dir = resolve(__dirname, "..");
  for (let i = 0; i < 5; i++) {
    const pkg = join(dir, "package.json");
    if (existsSync(pkg)) {
      try {
        const content = JSON.parse(readFileSync(pkg, "utf-8"));
        if (content.name === "clawpilot") return dir;
      } catch { /* skip */ }
    }
    dir = resolve(dir, "..");
  }
  // Fallback: assume CWD is the repo root
  return process.cwd();
}

// ── Step 1: .env ─────────────────────────────────────────────
async function setupEnv(repoRoot: string): Promise<void> {
  const envPath = join(repoRoot, ".env");

  console.log(`\n${BOLD}Step 1: Server Configuration (.env)${RESET}\n`);

  if (existsSync(envPath)) {
    const overwrite = await confirm(".env already exists. Overwrite?", false);
    if (!overwrite) {
      info("Keeping existing .env");
      return;
    }
  }

  const agentName = await ask("Agent name (shown in Teams cards)", "DevBox-1");
  const port = await ask("Server port", "3978");

  console.log(`
${BOLD}Teams Incoming Webhook Setup:${RESET}
${DIM}This lets ClawPilot send notifications to your Teams channel.${RESET}

  1. Open Microsoft Teams
  2. Go to the channel where you want notifications
  3. Click ${BOLD}•••${RESET} → ${BOLD}Manage channel${RESET} → ${BOLD}Connectors / Workflows${RESET}
  4. Search for ${BOLD}"Incoming Webhook"${RESET} or create a ${BOLD}Power Automate workflow${RESET}
     that posts Adaptive Cards
  5. Copy the webhook URL
`);

  const webhookUrl = await ask("Teams Webhook URL (paste here, or leave blank to skip)");

  console.log(`
${BOLD}Teams Outgoing Webhook Setup:${RESET}
${DIM}This lets you reply to the agent via @ClawPilot in Teams.${RESET}

  1. Open Teams → go to the Team (not channel)
  2. Click ${BOLD}•••${RESET} → ${BOLD}Manage team${RESET} → ${BOLD}Apps${RESET} → ${BOLD}Create an outgoing webhook${RESET}
  3. Name: ${BOLD}ClawPilot${RESET}
  4. Callback URL: You'll get this after starting the server (it needs a public URL)
  5. Copy the ${BOLD}HMAC security token${RESET} it generates
`);

  const webhookSecret = await ask("Outgoing Webhook HMAC Secret (or leave blank to skip)");

  const envContent = `# ── ClawPilot Environment Configuration ───────────────────────
# Generated by clawpilot init

AGENT_NAME=${agentName}
PORT=${port}

# Public URL — auto-provisioned via devtunnel on startup.
# Uncomment and set only if you want to use your own tunnel/proxy.
# PUBLIC_URL=https://your-tunnel.devtunnels.ms

# ── ClawPilot → Teams (outbound notifications) ───────────────
TEAMS_WEBHOOK_URL=${webhookUrl}

# ── Teams → ClawPilot (inbound replies via outgoing webhook) ──
OUTGOING_WEBHOOK_SECRET=${webhookSecret}
`;

  writeFileSync(envPath, envContent, "utf-8");
  success(`Created ${envPath}`);
}

// ── Step 2: .vscode/mcp.json ─────────────────────────────────
async function setupMcpJson(repoRoot: string): Promise<void> {
  console.log(`\n${BOLD}Step 2: MCP Server Configuration${RESET}\n`);

  const addMcp = await confirm("Add ClawPilot MCP server to a workspace?");
  if (!addMcp) return;

  const workspacePath = await ask(
    "Workspace path (where .vscode/mcp.json should be created)",
    process.cwd()
  );
  const resolvedWorkspace = resolve(workspacePath);

  const vscodeDir = join(resolvedWorkspace, ".vscode");
  const mcpPath = join(vscodeDir, "mcp.json");

  if (existsSync(mcpPath)) {
    const overwrite = await confirm("mcp.json already exists. Overwrite?", false);
    if (!overwrite) {
      info("Keeping existing mcp.json");
      return;
    }
  }

  const serverDistPath = join(repoRoot, "packages", "mcp-server", "dist", "index.js");

  const mcpContent = {
    servers: {
      clawpilot: {
        type: "stdio",
        command: "node",
        args: [serverDistPath.replace(/\\/g, "/")],
        env: {
          CLAWPILOT_SERVER_URL: "http://localhost:3978",
        },
      },
    },
  };

  mkdirSync(vscodeDir, { recursive: true });
  writeFileSync(mcpPath, JSON.stringify(mcpContent, null, 2) + "\n", "utf-8");
  success(`Created ${mcpPath}`);
}

// ── Step 3: Summary ──────────────────────────────────────────
function printSummary(repoRoot: string): void {
  console.log(`
${BOLD}${GREEN}Setup Complete!${RESET}

${BOLD}Next steps:${RESET}

  1. ${BOLD}Build${RESET} (if you haven't already):
     ${DIM}cd ${repoRoot}${RESET}
     ${DIM}npm install && npm run build${RESET}

  2. ${BOLD}Start the server${RESET}:
     ${DIM}cd ${repoRoot}${RESET}
     ${DIM}npm start${RESET}

     The server will print your public URL (via devtunnel).
     Use that URL as the ${BOLD}Callback URL${RESET} for the Teams outgoing webhook.

  3. ${BOLD}Reload VS Code${RESET} in your workspace:
     ${DIM}Ctrl+Shift+P → "Developer: Reload Window"${RESET}

     Copilot will auto-detect the MCP server. All 5 tools + auto-start are ready.
`);
}

// ── Main ─────────────────────────────────────────────────────
async function main() {
  banner();

  const repoRoot = findRepoRoot();
  info(`ClawPilot repo: ${repoRoot}`);

  await setupEnv(repoRoot);
  await setupMcpJson(repoRoot);
  printSummary(repoRoot);

  rl.close();
}

main().catch((err) => {
  console.error("Setup failed:", err);
  process.exit(1);
});
